version: "3.9"
services:
  poc-mariadb:
    image: bitnamilegacy/mariadb:10.6.7
    environment:
      - MARIADB_DATABASE=db
      - MARIADB_ROOT_PASSWORD=password

  run-poc-tests:
    image: "node:22.21.1"
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - PROJECTS
    entrypoint: >
      bash -c "npx nx run-many --target=test --projects=$$PROJECTS --parallel=1"
